<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDOJFp8S\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDOJFp8S/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerDOJFp8S.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerDOJFp8S\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerDOJFp8S\appAppKernelProdContainer([
    'container.build_hash' => 'DOJFp8S',
    'container.build_id' => '9e9f7373',
    'container.build_time' => 1710147193,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDOJFp8S');
