<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZCg7Weg\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZCg7Weg/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerZCg7Weg.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerZCg7Weg\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerZCg7Weg\appAppKernelProdContainer([
    'container.build_hash' => 'ZCg7Weg',
    'container.build_id' => '8bafeafe',
    'container.build_time' => 1710145550,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZCg7Weg');
