<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ7BRpGT\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ7BRpGT/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerZ7BRpGT.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerZ7BRpGT\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerZ7BRpGT\appAppKernelProdContainer([
    'container.build_hash' => 'Z7BRpGT',
    'container.build_id' => '85ac86bc',
    'container.build_time' => 1710150661,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ7BRpGT');
